//
//  PaintCube.m
//  TNKCube
//
//  Created by Larry Ryan on 5/17/14.
//  Copyright (c) 2014 Thinkr LLC.. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PaintCube.h"


@implementation PaintCube

#pragma mark Cache

static UIColor* _pomegranateColor = nil;
static UIColor* _pumpkinColor = nil;
static UIColor* _tangerineColor = nil;
static UIColor* _emerlandColor = nil;
static UIColor* _nephritisColor = nil;
static UIColor* _greenSeaColor = nil;
static UIColor* _belizeHoleColor = nil;
static UIColor* _wisteriaColor = nil;
static UIColor* _amethystColor = nil;
static UIColor* _asbestosColor = nil;
static UIColor* _concreteColor = nil;
static UIColor* _silverColor = nil;

static UIImage* _imageOfCube = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _pomegranateColor = [UIColor colorWithRed: 0.753 green: 0.224 blue: 0.169 alpha: 1];
    _pumpkinColor = [UIColor colorWithRed: 0.827 green: 0.329 blue: 0 alpha: 1];
    _tangerineColor = [UIColor colorWithRed: 0.953 green: 0.612 blue: 0.071 alpha: 1];
    _emerlandColor = [UIColor colorWithRed: 0.18 green: 0.8 blue: 0.443 alpha: 1];
    _nephritisColor = [UIColor colorWithRed: 0.153 green: 0.682 blue: 0.376 alpha: 1];
    _greenSeaColor = [UIColor colorWithRed: 0.086 green: 0.627 blue: 0.522 alpha: 1];
    _belizeHoleColor = [UIColor colorWithRed: 0.161 green: 0.502 blue: 0.725 alpha: 1];
    _wisteriaColor = [UIColor colorWithRed: 0.557 green: 0.267 blue: 0.678 alpha: 1];
    _amethystColor = [UIColor colorWithRed: 0.608 green: 0.349 blue: 0.714 alpha: 1];
    _asbestosColor = [UIColor colorWithRed: 0.498 green: 0.549 blue: 0.553 alpha: 1];
    _concreteColor = [UIColor colorWithRed: 0.584 green: 0.647 blue: 0.651 alpha: 1];
    _silverColor = [UIColor colorWithRed: 0.741 green: 0.765 blue: 0.78 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)pomegranateColor { return _pomegranateColor; }
+ (UIColor*)pumpkinColor { return _pumpkinColor; }
+ (UIColor*)tangerineColor { return _tangerineColor; }
+ (UIColor*)emerlandColor { return _emerlandColor; }
+ (UIColor*)nephritisColor { return _nephritisColor; }
+ (UIColor*)greenSeaColor { return _greenSeaColor; }
+ (UIColor*)belizeHoleColor { return _belizeHoleColor; }
+ (UIColor*)wisteriaColor { return _wisteriaColor; }
+ (UIColor*)amethystColor { return _amethystColor; }
+ (UIColor*)asbestosColor { return _asbestosColor; }
+ (UIColor*)concreteColor { return _concreteColor; }
+ (UIColor*)silverColor { return _silverColor; }

#pragma mark Drawing Methods

+ (void)drawCube;
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Graphic 0 Drawing
    UIBezierPath* graphic0Path = UIBezierPath.bezierPath;
    [graphic0Path moveToPoint: CGPointMake(11.39, 18.47)];
    [graphic0Path addLineToPoint: CGPointMake(22, 12.39)];
    [graphic0Path addLineToPoint: CGPointMake(32.61, 18.47)];
    [graphic0Path addLineToPoint: CGPointMake(22, 24.55)];
    [graphic0Path addLineToPoint: CGPointMake(11.39, 18.47)];
    [graphic0Path closePath];
    [PaintCube.silverColor setFill];
    [graphic0Path fill];


    //// Graphic 1 Drawing
    UIBezierPath* graphic1Path = UIBezierPath.bezierPath;
    [graphic1Path moveToPoint: CGPointMake(22.39, 25.22)];
    [graphic1Path addLineToPoint: CGPointMake(33, 19.14)];
    [graphic1Path addLineToPoint: CGPointMake(33, 31.37)];
    [graphic1Path addLineToPoint: CGPointMake(22.39, 37.39)];
    [graphic1Path addLineToPoint: CGPointMake(22.39, 25.22)];
    [graphic1Path closePath];
    [PaintCube.concreteColor setFill];
    [graphic1Path fill];


    //// Graphic 2 Drawing
    UIBezierPath* graphic2Path = UIBezierPath.bezierPath;
    [graphic2Path moveToPoint: CGPointMake(21.61, 37.39)];
    [graphic2Path addLineToPoint: CGPointMake(21.61, 25.22)];
    [graphic2Path addLineToPoint: CGPointMake(11, 19.14)];
    [graphic2Path addLineToPoint: CGPointMake(11, 31.3)];
    [graphic2Path addLineToPoint: CGPointMake(21.61, 37.39)];
    [graphic2Path closePath];
    [PaintCube.asbestosColor setFill];
    [graphic2Path fill];


    //// Graphic 3 Drawing
    UIBezierPath* graphic3Path = UIBezierPath.bezierPath;
    [graphic3Path moveToPoint: CGPointMake(0, 25)];
    [graphic3Path addLineToPoint: CGPointMake(10.22, 19.14)];
    [graphic3Path addLineToPoint: CGPointMake(10.22, 30.86)];
    [graphic3Path addLineToPoint: CGPointMake(0, 25)];
    [graphic3Path closePath];
    [PaintCube.amethystColor setFill];
    [graphic3Path fill];


    //// Graphic 12 Drawing
    UIBezierPath* graphic12Path = UIBezierPath.bezierPath;
    [graphic12Path moveToPoint: CGPointMake(44, 25)];
    [graphic12Path addLineToPoint: CGPointMake(33.78, 19.14)];
    [graphic12Path addLineToPoint: CGPointMake(33.78, 30.86)];
    [graphic12Path addLineToPoint: CGPointMake(44, 25)];
    [graphic12Path closePath];
    [PaintCube.amethystColor setFill];
    [graphic12Path fill];


    //// Graphic 13 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 39.09, 31.53);

    UIBezierPath* graphic13Path = UIBezierPath.bezierPath;
    [graphic13Path moveToPoint: CGPointMake(4.91, -5.63)];
    [graphic13Path addLineToPoint: CGPointMake(-4.91, -0)];
    [graphic13Path addLineToPoint: CGPointMake(4.91, 5.63)];
    [graphic13Path addLineToPoint: CGPointMake(4.91, -5.63)];
    [graphic13Path closePath];
    [PaintCube.wisteriaColor setFill];
    [graphic13Path fill];

    CGContextRestoreGState(context);


    //// Graphic 14 Drawing
    UIBezierPath* graphic14Path = UIBezierPath.bezierPath;
    [graphic14Path moveToPoint: CGPointMake(43.61, 37.84)];
    [graphic14Path addLineToPoint: CGPointMake(33.78, 43.47)];
    [graphic14Path addLineToPoint: CGPointMake(33.78, 32.2)];
    [graphic14Path addLineToPoint: CGPointMake(43.61, 37.84)];
    [graphic14Path closePath];
    [PaintCube.belizeHoleColor setFill];
    [graphic14Path fill];


    //// Graphic 15 Drawing
    UIBezierPath* graphic15Path = UIBezierPath.bezierPath;
    [graphic15Path moveToPoint: CGPointMake(33, 32.2)];
    [graphic15Path addLineToPoint: CGPointMake(33, 43.92)];
    [graphic15Path addLineToPoint: CGPointMake(22.79, 38.06)];
    [graphic15Path addLineToPoint: CGPointMake(33, 32.2)];
    [graphic15Path closePath];
    [PaintCube.greenSeaColor setFill];
    [graphic15Path fill];


    //// Graphic 16 Drawing
    UIBezierPath* graphic16Path = UIBezierPath.bezierPath;
    [graphic16Path moveToPoint: CGPointMake(32.22, 44.37)];
    [graphic16Path addLineToPoint: CGPointMake(22.39, 50)];
    [graphic16Path addLineToPoint: CGPointMake(22.39, 38.73)];
    [graphic16Path addLineToPoint: CGPointMake(32.22, 44.37)];
    [graphic16Path closePath];
    [PaintCube.nephritisColor setFill];
    [graphic16Path fill];


    //// Graphic 17 Drawing
    UIBezierPath* graphic17Path = UIBezierPath.bezierPath;
    [graphic17Path moveToPoint: CGPointMake(11.78, 44.37)];
    [graphic17Path addLineToPoint: CGPointMake(21.61, 50)];
    [graphic17Path addLineToPoint: CGPointMake(21.61, 38.74)];
    [graphic17Path addLineToPoint: CGPointMake(11.78, 44.37)];
    [graphic17Path closePath];
    [PaintCube.emerlandColor setFill];
    [graphic17Path fill];


    //// Graphic 18 Drawing
    UIBezierPath* graphic18Path = UIBezierPath.bezierPath;
    [graphic18Path moveToPoint: CGPointMake(11, 32.2)];
    [graphic18Path addLineToPoint: CGPointMake(11, 43.92)];
    [graphic18Path addLineToPoint: CGPointMake(21.22, 38.06)];
    [graphic18Path addLineToPoint: CGPointMake(11, 32.2)];
    [graphic18Path closePath];
    [PaintCube.tangerineColor setFill];
    [graphic18Path fill];


    //// Graphic 19 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 5.31, 37.84);

    UIBezierPath* graphic19Path = UIBezierPath.bezierPath;
    [graphic19Path moveToPoint: CGPointMake(4.91, -5.63)];
    [graphic19Path addLineToPoint: CGPointMake(4.91, 5.63)];
    [graphic19Path addLineToPoint: CGPointMake(-4.91, 0)];
    [graphic19Path addLineToPoint: CGPointMake(4.91, -5.63)];
    [graphic19Path closePath];
    [PaintCube.pumpkinColor setFill];
    [graphic19Path fill];

    CGContextRestoreGState(context);


    //// Graphic 20 Drawing
    UIBezierPath* graphic20Path = UIBezierPath.bezierPath;
    [graphic20Path moveToPoint: CGPointMake(0, 25.9)];
    [graphic20Path addLineToPoint: CGPointMake(9.83, 31.53)];
    [graphic20Path addLineToPoint: CGPointMake(0, 37.16)];
    [graphic20Path addLineToPoint: CGPointMake(0, 25.9)];
    [graphic20Path closePath];
    [PaintCube.pomegranateColor setFill];
    [graphic20Path fill];


    //// Group
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 29.34, 11.99);



        //// Graphic 8 Drawing
        UIBezierPath* graphic8Path = UIBezierPath.bezierPath;
        [graphic8Path moveToPoint: CGPointMake(2.87, -6.36)];
        [graphic8Path addLineToPoint: CGPointMake(-6.95, -0.72)];
        [graphic8Path addLineToPoint: CGPointMake(-6.95, -11.99)];
        [graphic8Path addLineToPoint: CGPointMake(2.87, -6.36)];
        [graphic8Path closePath];
        [PaintCube.emerlandColor setFill];
        [graphic8Path fill];


        //// Graphic 9 Drawing
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, -1.45, -0.05);

        UIBezierPath* graphic9Path = UIBezierPath.bezierPath;
        [graphic9Path moveToPoint: CGPointMake(5.11, -5.86)];
        [graphic9Path addLineToPoint: CGPointMake(5.11, 5.86)];
        [graphic9Path addLineToPoint: CGPointMake(-5.11, -0)];
        [graphic9Path addLineToPoint: CGPointMake(5.11, -5.86)];
        [graphic9Path closePath];
        [PaintCube.tangerineColor setFill];
        [graphic9Path fill];

        CGContextRestoreGState(context);


        //// Graphic 10 Drawing
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 9.35, 0.17);

        UIBezierPath* graphic10Path = UIBezierPath.bezierPath;
        [graphic10Path moveToPoint: CGPointMake(-4.91, 5.63)];
        [graphic10Path addLineToPoint: CGPointMake(-4.91, -5.63)];
        [graphic10Path addLineToPoint: CGPointMake(4.91, -0)];
        [graphic10Path addLineToPoint: CGPointMake(-4.91, 5.63)];
        [graphic10Path closePath];
        [PaintCube.pumpkinColor setFill];
        [graphic10Path fill];

        CGContextRestoreGState(context);


        //// Graphic 11 Drawing
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 9.74, 6.48);

        UIBezierPath* graphic11Path = UIBezierPath.bezierPath;
        [graphic11Path moveToPoint: CGPointMake(4.91, -5.63)];
        [graphic11Path addLineToPoint: CGPointMake(4.91, 5.63)];
        [graphic11Path addLineToPoint: CGPointMake(-4.91, 0)];
        [graphic11Path addLineToPoint: CGPointMake(4.91, -5.63)];
        [graphic11Path closePath];
        [PaintCube.pomegranateColor setFill];
        [graphic11Path fill];

        CGContextRestoreGState(context);



        CGContextRestoreGState(context);
    }


    //// Group 2
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, 10.8, 12.05);



        //// Graphic 4 Drawing
        UIBezierPath* graphic4Path = UIBezierPath.bezierPath;
        [graphic4Path moveToPoint: CGPointMake(-10.8, 0.95)];
        [graphic4Path addLineToPoint: CGPointMake(-10.8, 12.05)];
        [graphic4Path addLineToPoint: CGPointMake(-0.98, 6.42)];
        [graphic4Path addLineToPoint: CGPointMake(-10.8, 0.95)];
        [graphic4Path closePath];
        [PaintCube.wisteriaColor setFill];
        [graphic4Path fill];


        //// Graphic 5 Drawing
        UIBezierPath* graphic5Path = UIBezierPath.bezierPath;
        [graphic5Path moveToPoint: CGPointMake(-0.59, 5.74)];
        [graphic5Path addLineToPoint: CGPointMake(-0.59, -5.52)];
        [graphic5Path addLineToPoint: CGPointMake(-10.41, 0.11)];
        [graphic5Path addLineToPoint: CGPointMake(-0.59, 5.74)];
        [graphic5Path closePath];
        [PaintCube.belizeHoleColor setFill];
        [graphic5Path fill];


        //// Graphic 6 Drawing
        UIBezierPath* graphic6Path = UIBezierPath.bezierPath;
        [graphic6Path moveToPoint: CGPointMake(0.2, -5.97)];
        [graphic6Path addLineToPoint: CGPointMake(0.2, 5.74)];
        [graphic6Path addLineToPoint: CGPointMake(10.41, -0.11)];
        [graphic6Path addLineToPoint: CGPointMake(0.2, -5.97)];
        [graphic6Path closePath];
        [PaintCube.greenSeaColor setFill];
        [graphic6Path fill];


        //// Graphic 7 Drawing
        UIBezierPath* graphic7Path = UIBezierPath.bezierPath;
        [graphic7Path moveToPoint: CGPointMake(10.8, -0.79)];
        [graphic7Path addLineToPoint: CGPointMake(10.8, -12.05)];
        [graphic7Path addLineToPoint: CGPointMake(0.98, -6.42)];
        [graphic7Path addLineToPoint: CGPointMake(10.8, -0.79)];
        [graphic7Path closePath];
        [PaintCube.nephritisColor setFill];
        [graphic7Path fill];



        CGContextRestoreGState(context);
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfCube;
{
    if (_imageOfCube)
        return _imageOfCube;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(44, 50), NO, 0.0f);
    [PaintCube drawCube];
    _imageOfCube = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfCube;
}

#pragma mark Customization Infrastructure

- (void)setCubeTargets: (NSArray*)cubeTargets
{
    _cubeTargets = cubeTargets;

    for (id target in self.cubeTargets)
        [target setImage: PaintCube.imageOfCube];
}


@end
