//
//  PaintCube.h
//  TNKCube
//
//  Created by Larry Ryan on 5/17/14.
//  Copyright (c) 2014 Thinkr LLC.. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface PaintCube : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* cubeTargets;

// Colors
+ (UIColor*)pomegranateColor;
+ (UIColor*)pumpkinColor;
+ (UIColor*)tangerineColor;
+ (UIColor*)emerlandColor;
+ (UIColor*)nephritisColor;
+ (UIColor*)greenSeaColor;
+ (UIColor*)belizeHoleColor;
+ (UIColor*)wisteriaColor;
+ (UIColor*)amethystColor;
+ (UIColor*)asbestosColor;
+ (UIColor*)concreteColor;
+ (UIColor*)silverColor;

// Drawing Methods
+ (void)drawCube;

// Generated Images
+ (UIImage*)imageOfCube;

@end
